services:
    # 1. Define the Node.js application service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: cluster-app
        environment:
            - DATABASE_HOST=db
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=postgres
            - DATABASE_NAME=mydatabase
            - JWT_SECRET=mysecretkey
        ports:
            - '5000:5000'
        depends_on:
            - db
        volumes:
            - .:/app
            - /app/node_modules

    # 2. Define the PostgreSQL database service
    db:
        image: postgres:13-alpine
        container_name: cluster-db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=mydatabase
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

# 3. Define volumes to persist data
volumes:
    postgres_data:
